import Head from 'next/head'
import Layout from '../src/components/layout';
import Post from '../src/components/home/post';


export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post/>

    </Layout>
  )
}
